In [6]:
import torch
from torch import optim

# 02 Linear Regression

In [11]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

w = torch.zeros(1,requires_grad=True) # 0으로 초기화 / 항상 출력 0 예측
b = torch.zeros(1,requires_grad=True) # # requires_grad = True -> 학습할 것이라 명시


optimizer = optim.SGD([w,b], lr=0.01) # lr = learning rate

nb_epochs = 1000
for epoch  in range(1, nb_epochs + 1):
  hyphothesis = x_train*w + b
  cost = torch.mean((hyphothesis - y_train) ** 2)
  optimizer.zero_grad() # gradient 초기화
  cost.backward() # gradient 계산
  optimizer.step() # 개선

In [12]:
print(w)
print(b)

tensor([1.9708], requires_grad=True)
tensor([0.0664], requires_grad=True)


In [13]:
for i in [1,2,3]:
  print(i*w+b)

tensor([2.0372], grad_fn=<AddBackward0>)
tensor([4.0080], grad_fn=<AddBackward0>)
tensor([5.9788], grad_fn=<AddBackward0>)


# 03 Deeper Look at GD(Gradient Descent)

In [20]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[1],[2],[3]])

w = torch.zeros(1) # 0으로 초기화 / 항상 출력 0 예측
lr = 0.1

nb_epochs= 10
for epoch in range(nb_epochs+1):
  hyphothesis = x_train*w
  cost = torch.mean((hyphothesis - y_train) ** 2)
  gradient = 2 * torch.mean((w*x_train - y_train)*x_train)

  print('Epoch {:4d}/{} w: {:.3f}, Cost: {:.6f}'.format(
      epoch, nb_epochs, w.item(), cost.item()
  ))

  w -= lr*gradient


Epoch    0/10 w: 0.000, Cost: 4.666667
Epoch    1/10 w: 0.933, Cost: 0.020741
Epoch    2/10 w: 0.996, Cost: 0.000092
Epoch    3/10 w: 1.000, Cost: 0.000000
Epoch    4/10 w: 1.000, Cost: 0.000000
Epoch    5/10 w: 1.000, Cost: 0.000000
Epoch    6/10 w: 1.000, Cost: 0.000000
Epoch    7/10 w: 1.000, Cost: 0.000000
Epoch    8/10 w: 1.000, Cost: 0.000000
Epoch    9/10 w: 1.000, Cost: 0.000000
Epoch   10/10 w: 1.000, Cost: 0.000000


In [22]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[1],[2],[3]])

w = torch.zeros(1, requires_grad=True) # 0으로 초기화 / 항상 출력 0 예측
optimizer = optim.SGD([w], lr=0.15)

nb_epochs= 10
for epoch in range(nb_epochs+1):
  hyphothesis = x_train*w
  cost = torch.mean((hyphothesis - y_train) ** 2)
  gradient = 2 * torch.mean((w*x_train - y_train)*x_train)

  print('Epoch {:4d}/{} w: {:.3f}, Cost: {:.6f}'.format(
      epoch, nb_epochs, w.item(), cost.item()
  ))

  optimizer.zero_grad() # gradient 초기화
  cost.backward() # gradient 계산
  optimizer.step() # 개선

Epoch    0/10 w: 0.000, Cost: 4.666667
Epoch    1/10 w: 1.400, Cost: 0.746667
Epoch    2/10 w: 0.840, Cost: 0.119467
Epoch    3/10 w: 1.064, Cost: 0.019115
Epoch    4/10 w: 0.974, Cost: 0.003058
Epoch    5/10 w: 1.010, Cost: 0.000489
Epoch    6/10 w: 0.996, Cost: 0.000078
Epoch    7/10 w: 1.002, Cost: 0.000013
Epoch    8/10 w: 0.999, Cost: 0.000002
Epoch    9/10 w: 1.000, Cost: 0.000000
Epoch   10/10 w: 1.000, Cost: 0.000000


# 04-1 Multivariable Linear Regression

In [25]:
x_train = torch.FloatTensor([[73,80,75],
                             [93,88,93],
                             [89,91,90],
                             [96,98,100],
                             [73,66,70]])
y_train = torch.FloatTensor([[152],[185],[180],[196],[142]])

W = torch.zeros((3,1), requires_grad = True)
b = torch.zeros(1, requires_grad = True)
optimizer = optim.SGD([W,b], lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):
  #hypothesis = x1_train * w1 + x2_train * w2 + x3_train * w3 + b
  hypothesis = x_train.matmul(W) + b
  cost = torch.mean((hypothesis - y_train) ** 2)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
      epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
  ))

Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 hypothesis: tensor([67.2578, 80.8397, 79.6523, 86.7394, 61.6605]) Cost: 9298.520508
Epoch    2/20 hypothesis: tensor([104.9128, 126.0990, 124.2466, 135.3015,  96.1821]) Cost: 2915.712402
Epoch    3/20 hypothesis: tensor([125.9942, 151.4381, 149.2133, 162.4896, 115.5097]) Cost: 915.040527
Epoch    4/20 hypothesis: tensor([137.7967, 165.6247, 163.1911, 177.7112, 126.3307]) Cost: 287.936096
Epoch    5/20 hypothesis: tensor([144.4044, 173.5674, 171.0168, 186.2332, 132.3891]) Cost: 91.371063
Epoch    6/20 hypothesis: tensor([148.1035, 178.0143, 175.3980, 191.0042, 135.7812]) Cost: 29.758249
Epoch    7/20 hypothesis: tensor([150.1744, 180.5042, 177.8509, 193.6753, 137.6805]) Cost: 10.445267
Epoch    8/20 hypothesis: tensor([151.3336, 181.8983, 179.2240, 195.1707, 138.7440]) Cost: 4.391237
Epoch    9/20 hypothesis: tensor([151.9824, 182.6789, 179.9928, 196.0079, 139.3396]) Cost: 2.493121
Epoch   10/20 hypo

In [28]:
# nn.Module : pytorch에서 알아서 해준다

x_train = torch.FloatTensor([[73,80,75],
                             [93,88,93],
                             [89,91,90],
                             [96,98,100],
                             [73,66,70]])
y_train = torch.FloatTensor([[152],[185],[180],[196],[142]])


import torch.nn as nn
class MultivariateLinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(3,1)
  def forward(self, x):
    return self.linear(x)



import torch.nn.functional as F


model = MultivariateLinearRegressionModel()

optimizer = optim.SGD(model.parameters(), lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):
  hypothesis = model(x_train)

  cost = F.mse_loss(hypothesis, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
      epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
  ))

Epoch    0/20 hypothesis: tensor([-61.3367, -73.0397, -72.3203, -78.5732, -55.7213]) Cost: 58049.335938
Epoch    1/20 hypothesis: tensor([32.7549, 40.0521, 39.1106, 42.7723, 30.5394]) Cost: 18196.263672
Epoch    2/20 hypothesis: tensor([ 85.4332, 103.3681, 101.4966, 110.7091,  78.8337]) Cost: 5704.439453
Epoch    3/20 hypothesis: tensor([114.9256, 138.8166, 136.4242, 148.7444, 105.8721]) Cost: 1788.917236
Epoch    4/20 hypothesis: tensor([131.4372, 158.6629, 155.9788, 170.0389, 121.0100]) Cost: 561.608154
Epoch    5/20 hypothesis: tensor([140.6813, 169.7743, 166.9267, 181.9609, 129.4854]) Cost: 176.911697
Epoch    6/20 hypothesis: tensor([145.8566, 175.9953, 173.0560, 188.6355, 134.2305]) Cost: 56.329285
Epoch    7/20 hypothesis: tensor([148.7539, 179.4782, 176.4875, 192.3724, 136.8873]) Cost: 18.532799
Epoch    8/20 hypothesis: tensor([150.3758, 181.4284, 178.4086, 194.4645, 138.3750]) Cost: 6.685200
Epoch    9/20 hypothesis: tensor([151.2837, 182.5202, 179.4841, 195.6357, 139.2079]) 

In [31]:
hypothesis.squeeze()

tensor([152.4332, 183.9092, 180.8489, 197.1220, 140.2691],
       grad_fn=<SqueezeBackward0>)

# 04-2 Loading Data

In [45]:
from torch.utils.data import Dataset

class CustomDataset(Dataset):
  def __init__(self):
    self.x_data = [[73,80,75],
                   [93,88,93],
                   [89,91,90],
                   [96,98,100],
                   [73,66,70]]
    self.y_data = [[152],[185],[180],[196],[142]]
  def __len__(self):
    return len(self.x_data)
  def __getitem__(self, idx):
    x = torch.FloatTensor(self.x_data[idx])
    y = torch.FloatTensor(self.y_data[idx])
    
    return x,y

dataset = CustomDataset()

##########
from torch.utils.data import DataLoader

dataloader = DataLoader(
    dataset,
    batch_size=2,
    shuffle=True
)

##########
nb_epochs = 20
for epoch in range(nb_epochs+1):
  for batch_idx, samples in enumerate(dataloader):
    x_train, y_train = samples
    prediction = model(x_train)

    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, batch_idx+1,len(dataloader), cost.item()
    ))

Epoch    0/20 Batch 1/3 Cost: 1.668824
Epoch    0/20 Batch 2/3 Cost: 1.334829
Epoch    0/20 Batch 3/3 Cost: 1.478034
Epoch    1/20 Batch 1/3 Cost: 1.068885
Epoch    1/20 Batch 2/3 Cost: 2.564916
Epoch    1/20 Batch 3/3 Cost: 0.822756
Epoch    2/20 Batch 1/3 Cost: 1.881890
Epoch    2/20 Batch 2/3 Cost: 0.933667
Epoch    2/20 Batch 3/3 Cost: 2.379152
Epoch    3/20 Batch 1/3 Cost: 0.465805
Epoch    3/20 Batch 2/3 Cost: 1.653504
Epoch    3/20 Batch 3/3 Cost: 2.089281
Epoch    4/20 Batch 1/3 Cost: 0.258716
Epoch    4/20 Batch 2/3 Cost: 2.451457
Epoch    4/20 Batch 3/3 Cost: 1.642032
Epoch    5/20 Batch 1/3 Cost: 1.403114
Epoch    5/20 Batch 2/3 Cost: 0.937763
Epoch    5/20 Batch 3/3 Cost: 2.801752
Epoch    6/20 Batch 1/3 Cost: 1.403082
Epoch    6/20 Batch 2/3 Cost: 1.161310
Epoch    6/20 Batch 3/3 Cost: 2.734477
Epoch    7/20 Batch 1/3 Cost: 1.131004
Epoch    7/20 Batch 2/3 Cost: 1.353042
Epoch    7/20 Batch 3/3 Cost: 3.170297
Epoch    8/20 Batch 1/3 Cost: 1.497991
Epoch    8/20 Batch 2/3 C

# 05 Logistic Regression

In [56]:
# P(x==0) == 1 - P(X==1)
# H(x) = P(x=1;w) = 1 - P(x=0;w)
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

In [72]:
x_data = [[1,2], [2,3], [3,1], [4,3], [5,3], [6,2]]
y_data = [[0],[0],[0],[1],[1],[1]]

In [73]:
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)
print(x_train.shape)
print(y_train.shape)

torch.Size([6, 2])
torch.Size([6, 1])


In [74]:
print('e^1 equals: ', torch.exp(torch.FloatTensor([1])))

e^1 equals:  tensor([2.7183])


In [92]:
w = torch.zeros((2,1), requires_grad=True)
d = torch.zeros(1,requires_grad=True)

In [93]:
hypothesis = 1 / (1+ torch.exp(-(x_train.matmul(w) + d))) # x*w = torch.matmul(x,w)
print(hypothesis)
print(hypothesis.shape)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<MulBackward0>)
torch.Size([6, 1])


In [94]:
print('1/(1+e^{-1}) equals: ', torch.sigmoid(torch.FloatTensor([1])))

1/(1+e^{-1}) equals:  tensor([0.7311])


In [95]:
hypothesis = torch.sigmoid(x_train.matmul(w)+ d)
print(hypothesis)
print(hypothesis.shape)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<SigmoidBackward0>)
torch.Size([6, 1])


In [96]:
print(hypothesis)
print(y_train)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<SigmoidBackward0>)
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])


In [97]:
losses = -(y_train*torch.log(hypothesis) + (1 - y_train) * torch.log(1-hypothesis))
print(losses)

tensor([[0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931]], grad_fn=<NegBackward0>)


In [98]:
cost = losses.mean()
print(cost)

tensor(0.6931, grad_fn=<MeanBackward0>)


In [99]:
# 앞것들 한번에
F.binary_cross_entropy(hypothesis,y_train)

tensor(0.6931, grad_fn=<BinaryCrossEntropyBackward0>)

In [101]:
optimizer = optim.SGD([w,d], lr=1)
nb_epochs = 1000
for epoch in range(nb_epochs + 1):
  hypothesis = torch.sigmoid(x_train.matmul(w) + d)
  cost = F.binary_cross_entropy(hypothesis, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
    ))

RuntimeError: ignored

In [102]:
hypothesis = torch.sigmoid(x_train.matmul(w) + d)
print(hypothesis[:5])

RuntimeError: ignored

In [ ]:
prediction = hypothesis >= torch.FloatTensor([0.5])
print(prediction[:5])

In [103]:
print(prediction[:5])
print(y_train[:5])

tensor([[False],
        [False],
        [False],
        [ True],
        [ True]])
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.]])


In [104]:
correct_prediction = prediction.float() == y_train
print(correct_prediction[:5])

tensor([[True],
        [True],
        [True],
        [True],
        [True]])


In [107]:
# class
class BinaryClssifier(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(2,1)
    self.sigmoid = nn.Sigmoid()
  def forward(self, x):
    return self.sigmoid(self.linear(x))

model = BinaryClssifier()

In [108]:
optimizer = optim.SGD(model.parameters(), lr=1)

nb_epochs = 100
for epoch in range(nb_epochs+1):

  hypothesis = model(x_train)
  cost = F.binary_cross_entropy(hypothesis, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 10 == 0:
    prediction = hypothesis >= torch.FloatTensor([0.5])
    correct_prediction = prediction.float() == y_train
    accuracy = correct_prediction.sum().item() / len(correct_prediction)
    print('Epoch {:4d}/{} Cost: {:.6f} Accuracy {:2.2f}%'.format(
        epoch, nb_epochs, cost.item(), accuracy * 100
    ))

Epoch    0/100 Cost: 0.841201 Accuracy 50.00%
Epoch   10/100 Cost: 0.457889 Accuracy 66.67%
Epoch   20/100 Cost: 0.423259 Accuracy 83.33%
Epoch   30/100 Cost: 0.355104 Accuracy 83.33%
Epoch   40/100 Cost: 0.300464 Accuracy 83.33%
Epoch   50/100 Cost: 0.251668 Accuracy 83.33%
Epoch   60/100 Cost: 0.207725 Accuracy 100.00%
Epoch   70/100 Cost: 0.172860 Accuracy 100.00%
Epoch   80/100 Cost: 0.152507 Accuracy 100.00%
Epoch   90/100 Cost: 0.140916 Accuracy 100.00%
Epoch  100/100 Cost: 0.131552 Accuracy 100.00%
