In [2]:
import numpy as np
import torch

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print('rank of t  : ', t.ndim)
print('shape of t : ', t.shape)

rank of t  :  1
shape of t :  (7,)


In [4]:
print('t[-1] : ', t[-1])
print('t[2:5] : ', t[2:5])
print('t[:2] : ', t[:2])

t[-1] :  6.0
t[2:5] :  [2. 3. 4.]
t[:2] :  [0. 1.]


In [5]:
t = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]])
print(t)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [6]:
print('rank of t  : ', t.ndim)
print('shape of t : ', t.shape)

rank of t  :  2
shape of t :  (3, 3)


In [7]:
t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [10]:
print(t.dim())
print(t.shape)
print(t.size())
print(t[-1])
print(t[2:5])
print(t[:2])

1
torch.Size([7])
torch.Size([7])
tensor(6.)
tensor([2., 3., 4.])
tensor([0., 1.])


In [11]:
t = torch.FloatTensor([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]])
print(t)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [14]:
print(t.dim())
print(t.shape)
print(t.size())
print(t[:,1])
print(t[:,1].size())
print(t[:2,:-1])

2
torch.Size([3, 3])
torch.Size([3, 3])
tensor([2., 5., 8.])
torch.Size([3])
tensor([[1., 2.],
        [4., 5.]])


Broadcasting

In [15]:
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1+m2)

tensor([[5., 5.]])


In [16]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3])
print(m1+m2)

tensor([[4., 5.]])


In [17]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1+m2)

tensor([[4., 5.],
        [5., 6.]])


In [18]:
print()
print('-------------')
print('Mul vs Matmul')
print('-------------')
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))


-------------
Mul vs Matmul
-------------
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [19]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [20]:
t = torch.LongTensor([1,2])
try:
  print(t.mean())
except Exception as exc:
  print(exc)

mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long


In [21]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [22]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [23]:
# sum
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [24]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [25]:
#max
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [26]:
print(t.max())

tensor(4.)


In [27]:
print(t.max(dim=0))
print('max: ',t.max(dim=0)[0])
print('argmax: ', t.max(dim=0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
max:  tensor([3., 4.])
argmax:  tensor([1, 1])


In [28]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


2_2

In [3]:
# view
t = np.array([[[0,1,2],
              [3,4,5]],
             
             [[6,7,8],
              [9,10,11]]])
ft = torch.FloatTensor(t)
print(ft.shape)


torch.Size([2, 2, 3])


In [4]:
print(ft.view([-1,3]))
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [5]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [17]:
# squeeze
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [19]:
print(ft.squeeze())
print(ft.squeeze().shape)
print(ft.squeeze(dim=1))

tensor([0., 1., 2.])
torch.Size([3])
tensor([0., 1., 2.])


In [55]:
#Unsqueeze
ft = torch.Tensor([0, 1, 2, 3])
print(ft)
print(ft.shape)

tensor([0., 1., 2., 3.])
torch.Size([4])


In [56]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2., 3.]])
torch.Size([1, 4])


In [27]:
print(ft.view(1,-1))
print(ft.view(1,-1).shape)

tensor([[0., 1., 2., 3.]])
torch.Size([1, 4])


In [54]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2., 3.]])
torch.Size([1, 4])


In [33]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.],
        [3.]])
torch.Size([4, 1])


In [34]:
print(ft.view(2,-1))
print(ft.view(2,-1).shape)

tensor([[0., 1.],
        [2., 3.]])
torch.Size([2, 2])


In [36]:
print(ft.view(-1,2))
print(ft.view(-1,2).shape)

tensor([[0., 1.],
        [2., 3.]])
torch.Size([2, 2])


In [40]:
print(ft.view(-1,1,1))
print(ft.view(-1,1,1).shape)

tensor([[[0.]],

        [[1.]],

        [[2.]],

        [[3.]]])
torch.Size([4, 1, 1])


In [42]:
# Type Casting
lt = torch.LongTensor([1,2,3,4])
print(lt)
print(lt.float())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])


In [43]:
bt = torch.ByteTensor([True,False,False,True])
print(bt)
print(bt.long()) # 정수
print(bt.float()) # float

tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [49]:
bt2 = (lt==2)
print(bt2)
print(bt2.long()) # 정수
print(bt2.float()) # float

tensor([False,  True, False, False])
tensor([0, 1, 0, 0])
tensor([0., 1., 0., 0.])


In [51]:
# Concatenate
x = torch.FloatTensor([[1,2,9], [3,4,10]])
y = torch.FloatTensor([[5,6,11], [7,8,12]])

# dim이 늘어남
print(torch.cat([x,y],dim=0))
print(torch.cat([x,y],dim=1))

tensor([[ 1.,  2.,  9.],
        [ 3.,  4., 10.],
        [ 5.,  6., 11.],
        [ 7.,  8., 12.]])
tensor([[ 1.,  2.,  9.,  5.,  6., 11.],
        [ 3.,  4., 10.,  7.,  8., 12.]])


In [61]:
 # Stacking

x = torch.FloatTensor([1, 4,7])
y = torch.FloatTensor([2, 5,8])
z = torch.FloatTensor([3, 9,6])

print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim=1))

tensor([[1., 4., 7.],
        [2., 5., 8.],
        [3., 9., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 9.],
        [7., 8., 6.]])


In [62]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4., 7.],
        [2., 5., 8.],
        [3., 9., 6.]])


In [63]:
# Ones zeros
x = torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [64]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [65]:
# In-place Operation
x = torch.FloatTensor([[1, 2], [3, 4]])

print(x.mul(2.))
print(x)
print(x.mul_(2.)) # _(언더바)를 넣으면 반영이 됨
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


In [66]:
# zip
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [67]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9
